export const TOGGLE_ADD_TODOLIST_DIALOG = "TOGGLE_ADD_TODOLIST_DIALOG";
export const TOGGLE_EDIT_TODOLIST_DIALOG = "TOGGLE_EDIT_TODOLIST_DIALOG";

export const UPDATE_CURRENT_TODOLIST = "UPDATE_CURRENT_TODOLIST";
export const UPDATE_TEMP_TODOLIST = "UPDATE_TEMP_TODOLIST";

export const SAVE_TODOLISTS = "SAVE_TODOLISTS";

export const ADD_TODOLIST_REQUEST = "ADD_TODOLIST_REQUEST";
export const ADD_TODOLIST_SUCCESS = "ADD_TODOLIST_SUCCESS";
export const ADD_TODOLIST_FAILURE = "ADD_TODOLIST_FAILURE";

export const EDIT_TODOLIST_REQUEST = "EDIT_TODOLIST_REQUEST";
export const EDIT_TODOLIST_SUCCESS = "EDIT_TODOLIST_SUCCESS";
export const EDIT_TODOLIST_FAILURE = "EDIT_TODOLIST_FAILURE";

export const GET_TODOLISTS_REQUEST = "GET_TODOLISTS_REQUEST";
export const GET_TODOLISTS_SUCCESS = "GET_TODOLISTS_SUCCESS";
export const GET_TODOLISTS_FAILURE = "GET_TODOLISTS_FAILURE";

export const DELETE_TODOLIST_REQUEST = "DELETE_TODOLIST_REQUEST";
export const DELETE_TODOLIST_SUCCESS = "DELETE_TODOLIST_SUCCESS";
export const DELETE_TODOLIST_FAILURE = "DELETE_TODOLIST_FAILURE";

export const CLEAR_TODOS = "CLEAR_TODOS";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE";
