export const TOGGLE_ADD_TODOLIST_DIALOG = "TOGGLE_ADD_TODOLIST_DIALOG";
export const TOGGLE_EDIT_TODOLIST_DIALOG = "TOGGLE_EDIT_CALENDAR_DIALOG";

export const UPDATE_TEMP_EVENT = "UPDATE_TEMP_EVENT";
export const UPDATE_TEMP_TODOLIST = "UPDATE_TEMP_TODOLIST";

export const SAVE_CALENDARS = "SAVE_CALENDARS";

export const ADD_TODOLIST_REQUEST = "ADD_TODOLIST_REQUEST";
export const ADD_TODOLIST_SUCCESS = "ADD_TODOLIST_SUCCESS";
export const ADD_TODOLIST_FAILURE = "ADD_TODOLIST_FAILURE";

export const EDIT_TODOLIST_REQUEST = "EDIT_TODOLIST_REQUEST";
export const EDIT_TODOLIST_SUCCESS = "EDIT_TODOLIST_SUCCESS";
export const EDIT_TODOLIST_FAILURE = "EDIT_TODOLIST_FAILURE";

export const GET_TODOLISTS_REQUEST = "GET_TODOLISTS_REQUEST";
export const GET_TODOLISTS_SUCCESS = "GET_TODOLISTS_SUCCESS";
export const GET_TODOLISTS_FAILURE = "GET_TODOLISTS_FAILURE";

export const DELETE_TODOLIST_REQUEST = "DELETE_TODOLIST_REQUEST";
export const DELETE_TODOLIST_SUCCESS = "DELETE_TODOLIST_SUCCESS";
export const DELETE_TODOLIST_FAILURE = "DELETE_TODOLIST_FAILURE";

export const CLEAR_EVENTS = "CLEAR_EVENTS";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";
