export const TOGGLE_ADD_EVENT_DIALOG = "TOGGLE_ADD_EVENT_DIALOG";
export const TOGGLE_ADD_CALENDAR_DIALOG = "TOGGLE_ADD_CALENDAR_DIALOG";
export const TOGGLE_EDIT_CALENDAR_DIALOG = "TOGGLE_EDIT_CALENDAR_DIALOG";

export const UPDATE_TEMP_EVENT = "UPDATE_TEMP_EVENT";
export const UPDATE_TEMP_CALENDAR = "UPDATE_TEMP_CALENDAR";

export const SAVE_CALENDARS = "SAVE_CALENDARS";

export const ADD_CALENDAR_REQUEST = "ADD_CALENDAR_REQUEST";
export const ADD_CALENDAR_SUCCESS = "ADD_CALENDAR_SUCCESS";
export const ADD_CALENDAR_FAILURE = "ADD_CALENDAR_FAILURE";

export const EDIT_CALENDAR_REQUEST = "EDIT_CALENDAR_REQUEST";
export const EDIT_CALENDAR_SUCCESS = "EDIT_CALENDAR_SUCCESS";
export const EDIT_CALENDAR_FAILURE = "EDIT_CALENDAR_FAILURE";

export const GET_CALENDARS_REQUEST = "GET_CALENDARS_REQUEST";
export const GET_CALENDARS_SUCCESS = "GET_CALENDARS_SUCCESS";
export const GET_CALENDARS_FAILURE = "GET_CALENDARS_FAILURE";

export const DELETE_CALENDAR_REQUEST = "DELETE_CALENDAR_REQUEST";
export const DELETE_CALENDAR_SUCCESS = "DELETE_CALENDAR_SUCCESS";
export const DELETE_CALENDAR_FAILURE = "DELETE_CALENDAR_FAILURE";

export const CLEAR_EVENTS = "CLEAR_EVENTS";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";
