const actionTypes = {
  // Users action types
  RESET_CURRENT_USER: 'RESET_CURRENT_USER',

  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',

  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE'

  // LOGOUT: 'LOGOUT',
};

export default actionTypes;
