export const TOGGLE_ADD_NOTEBOOK_DIALOG = "TOGGLE_ADD_NOTEBOOK_DIALOG";
export const TOGGLE_EDIT_NOTEBOOK_DIALOG = "TOGGLE_EDIT_NOTEBOOK_DIALOG";

export const UPDATE_CURRENT_NOTEBOOK = "UPDATE_CURRENT_NOTEBOOK";
export const UPDATE_TEMP_NOTEBOOK = "UPDATE_TEMP_NOTEBOOK";

export const SAVE_NOTEBOOKS = "SAVE_NOTEBOOKS";

export const ADD_NOTEBOOK_REQUEST = "ADD_NOTEBOOK_REQUEST";
export const ADD_NOTEBOOK_SUCCESS = "ADD_NOTEBOOK_SUCCESS";
export const ADD_NOTEBOOK_FAILURE = "ADD_NOTEBOOK_FAILURE";

export const EDIT_NOTEBOOK_REQUEST = "EDIT_NOTEBOOK_REQUEST";
export const EDIT_NOTEBOOK_SUCCESS = "EDIT_NOTEBOOK_SUCCESS";
export const EDIT_NOTEBOOK_FAILURE = "EDIT_NOTEBOOK_FAILURE";

export const GET_NOTEBOOKS_REQUEST = "GET_NOTEBOOKS_REQUEST";
export const GET_NOTEBOOKS_SUCCESS = "GET_NOTEBOOKS_SUCCESS";
export const GET_NOTEBOOKS_FAILURE = "GET_NOTEBOOKS_FAILURE";

export const DELETE_NOTEBOOK_REQUEST = "DELETE_NOTEBOOK_REQUEST";
export const DELETE_NOTEBOOK_SUCCESS = "DELETE_NOTEBOOK_SUCCESS";
export const DELETE_NOTEBOOK_FAILURE = "DELETE_NOTEBOOK_FAILURE";

export const UPDATE_CURRENT_NOTE = "UPDATE_CURRENT_NOTE";

export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";

export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE";

export const EDIT_NOTE_REQUEST = "EDIT_NOTE_REQUEST";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_FAILURE = "EDIT_NOTE_FAILURE";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";
